# Setup
title:        Blogs by Jogendra
tagline:      Blogs for https://jogendra.github.io
baseurl:      "/blogs"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Jogendra Kumar
  url:        https://jogendra.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
