# Setup
title:        Blogs by Jogendra
baseurl:      "/blogs"
paginate:     1
locale:       "en"
permalink: /:title/

# About/contact
author:
  name:       Jogendra Kumar
  url:        https://jogendra.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
